apiVersion: apps/v1
kind: Deployment
metadata:
  name: panelku
  labels:
    app: panelku
spec:
  replicas: 1
  selector:
    matchLabels:
      app: panelku
  template:
    metadata:
      labels:
        app: panelku
    spec:
      containers:
        - name: panelku
          image: victor3232/panelku:latest
          imagePullPolicy: Always   # selalu tarik versi terbaru
          ports:
            - containerPort: 3000   # ganti sesuai port app kamu
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: panelku-service
spec:
  type: LoadBalancer
  selector:
    app: panelku
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      
